### PR TITLE
Noetic devel

### PR DESCRIPTION
**Pull request by KKalem**
Fix(hopefully) the mission_complete issue and some launch file problems that I found on the way.

### CODE REVIEW

**Comment by nilsbore** [comment]
If you get my `test_mission` branch and then run `roslaunch smarc_mission_sim mission_sim.launch`, you can watch a mission being run in neptus. Don't know if it will show correctly in neptus if the plan does not come from there? So not sure if you can test this that way?

**Comment by nilsbore** [comment]
@KKalem Can you merge main `noetic-devel` to this branch? Then we can check if the mission test still passes.

**Comment by KKalem** [comment]
Cool, its working it seems. Already caught a typo.

**Comment by KKalem** [comment]
Now im getting a time limit of 60s error. What is supposed to happen within 60s?

**Comment by nilsbore** [comment]
Hmm, rostest seems to impose a 60s restriction on the test. I set a 100s time to finish the mission. Will see if there is someway to extend rostest time alloted.

**Comment by nilsbore** [comment]
But a likely explanation is that you changed the waypoint tolerance: https://github.com/smarc-project/smarc_missions/pull/33/files#diff-911845a68ece7ce88eed6279b054bf3db266a7aaa1fc7a10183d63f049c41c4bR34 . So it probably didn't get to the goal because of that. Can we keep it at 5m?

**Comment by nilsbore** [comment]
I took some liberties with your branch ;)

**Comment by nilsbore** [comment]
I tested this locally also, both current `noetic-devel` (works) and your branch (does not). Mission does not start any more. Any ideas why?

**Comment by nilsbore** [comment]
It receives the plan but seems it does not respond to the start plan command any more. You can test yourself with `roslaunch smarc_mission_sim mission_sim.launch`. It sends a plan and the start command.

**Comment by iyuner** [comment]
FIIIIEXD /O

**Pull request merged**
